name: tarantula_identifier
description: App to identify tarantulas
version: 1.0.3+3

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons:    # Enable Cupertino Icons font
  firebase_admob:     # Enable AdMob
  flutter_spinkit:    # Enable spinner
  image_picker:       # Enable image picker
  shared_preferences: # Enable shared prefs

dev_dependencies:
  flutter_launcher_icons:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"