name: tarantula_identifier
description: App to identify tarantulas
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons:    # Enable Cupertino Icons font
  firebase_admob:     # Enable AdMob
  flutter_spinkit:    # Enable spinner
  image_picker:       # Enable image picker

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/